# Generated by Django 5.1.1 on 2024-09-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_product_delete_moodentry_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
